### ISSUE TITLE
Ufak Öneri

### ISSUE THREAD

**Issue by violencedev** [dolpsoft/KELIME-CUMLE-ANALIZI#1]
Gayet güzel fakat ufak önerim var bir tane. PEP8 Python yazım stiline alışsan iyi olur, ben de yavaş yavaş geçiş sağlıyorum. (bkz: https://peps.python.org/pep-0008/ )

Aynı zamanda bazı yorum satırları gereksiz, onlara da dikkat edersen iyi olur. Class'ın hemen altına multi-lined comment ile dokümantasyon oluşturabilirsin. 

Güzel fikir, kodun tamamını okumadım fakat detaylı analizi akşam eve geçince yapacağım. :)

**Comment by dolpsoft** [comment]
Eleştiriler için çok sağol, kodu baya eskiden yazmıştım ve tabi o zamanlar bende PEP8 falan yok :D (şuan da pek olduğu söylenemez ama neyse...)

![Screenshot_2022-05-18-23-15-08-86_320a9a695de7cdce83ed5281148d6f19](https://user-images.githubusercontent.com/86978234/169148406-65c3a82e-8872-44d6-94c7-96737515d394.jpg)

şuradaki kodları okudun mu bilmiyorum ama ben tekrar bakınca "bunlar ney" demekten kendimi alamadım :p

**Comment by violencedev** [comment]
Ow ow, :)))
